// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['media']['Service']['Create'](arg1, arg2);
}

export function FindAll(arg1) {
  return window['go']['media']['Service']['FindAll'](arg1);
}

export function FindByCode(arg1, arg2) {
  return window['go']['media']['Service']['FindByCode'](arg1, arg2);
}

export function FindByID(arg1, arg2) {
  return window['go']['media']['Service']['FindByID'](arg1, arg2);
}

export function FindOne(arg1, arg2) {
  return window['go']['media']['Service']['FindOne'](arg1, arg2);
}
