// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {media} from '../models';
import {ent} from '../models';

export function Create(arg1:context.Context,arg2:media.CreateInput):Promise<ent.Media>;

export function FindAll(arg1:context.Context):Promise<Array<ent.Media>>;

export function FindByCode(arg1:context.Context,arg2:string):Promise<ent.Media>;

export function FindByID(arg1:context.Context,arg2:string):Promise<ent.Media>;

export function FindOne(arg1:context.Context,arg2:string):Promise<ent.Media>;
