// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {ent} from '../models';

export function Create(arg1:media.CreateInput):Promise<ent.Media>;

export function DeleteById(arg1:string):Promise<void>;

export function FindAll():Promise<Array<ent.Media>>;

export function FindByCode(arg1:string):Promise<ent.Media>;

export function FindByID(arg1:string):Promise<ent.Media>;

export function Update(arg1:string,arg2:media.UpdatePayloadInput):Promise<ent.Media>;
