// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['media']['Service']['Create'](arg1);
}

export function DeleteById(arg1) {
  return window['go']['media']['Service']['DeleteById'](arg1);
}

export function FindAll() {
  return window['go']['media']['Service']['FindAll']();
}

export function FindByCode(arg1) {
  return window['go']['media']['Service']['FindByCode'](arg1);
}

export function FindByID(arg1) {
  return window['go']['media']['Service']['FindByID'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['media']['Service']['Update'](arg1, arg2);
}
