// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['actor']['Service']['Create'](arg1, arg2);
}

export function DeleteByID(arg1, arg2) {
  return window['go']['actor']['Service']['DeleteByID'](arg1, arg2);
}

export function FindByID(arg1, arg2) {
  return window['go']['actor']['Service']['FindByID'](arg1, arg2);
}

export function Update(arg1, arg2, arg3) {
  return window['go']['actor']['Service']['Update'](arg1, arg2, arg3);
}
