// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {actor} from '../models';
import {ent} from '../models';

export function Create(arg1:context.Context,arg2:actor.CreateInput):Promise<ent.Actor>;

export function DeleteByID(arg1:context.Context,arg2:string):Promise<void>;

export function FindByID(arg1:context.Context,arg2:string):Promise<ent.Actor>;

export function Update(arg1:context.Context,arg2:string,arg3:actor.UpdateInput):Promise<ent.Actor>;
